compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      "@graphql-tools/apollo-engine-loader": "*"
  "@rushstack/eslint-patch@*":
    dependencies:
      "@eslint/eslintrc": "*"
  "@types/react-dom@*":
    peerDependencies:
      react: "*"
  "@types/react@*":
    dependencies:
      prop-types: "*"
      scheduler: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-config-next@*:
    dependencies:
      "@eslint/eslintrc": "*"
      next: "*"
      react: "*"
      react-dom: "*"
  next@*:
    dependencies:
      sharp: "*"

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.3.1.cjs
